apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  type: NodePort
  ports:
    - port: 8899
      targetPort: 8899
      name: http
  selector:
    name: postgresql