apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claim.name }}
spec:
  storageClassName: {{ .Values.volume.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi